#!/bin/bash
aktuellesGesameltesAbwasser=$(echo $1);
gesamteFilterMengeInLiter=$(echo $2);
pumpeRelaisNr=$(echo $3);
gpd=$(echo $4);
warnLimitAbFilterMenge=$(echo $5);
filterZeitFuerNullKommaEinsLiterInSekunden=$(echo $6);
faktorGefiltertZuAbwasser=$(echo $7);
maxLiterAbwasserKanister=$(echo $8);
reinigungszeitInSekunden=$(echo $9);

echo ";EnergieBox
;Konfigurationsdatei für h2o
;Autogenerated by h2o -setup

[h2o]
aktuellesGesameltesAbwasser = $aktuellesGesameltesAbwasser
gesamteFilterMengeInLiter = $gesamteFilterMengeInLiter
pumpeRelaisNr = $pumpeRelaisNr
gpd = $gpd
warnLimitAbFilterMenge = $warnLimitAbFilterMenge
filterZeitFuerNullKommaEinsLiterInSekunden = $filterZeitFuerNullKommaEinsLiterInSekunden
faktorGefiltertZuAbwasser = $faktorGefiltertZuAbwasser
maxLiterAbwasserKanister = $maxLiterAbwasserKanister
reinigungszeitInSekunden = $reinigungszeitInSekunden
" > /Energiebox/h2o/config.ini
