#!/bin/bash

ventil_pumpe=$(echo $1);
hex_generator=$(echo $2);
filter_gpd=$(echo $3);
filter_max_menge_filtern=$(echo $4);
filter_verhaeltnis=$(echo $5);
filter_clean_time=$(echo $6);
filter_zeit_100ml=$(echo $7);
filter_total_liter=$(echo $8);
abwassertank_vorhanden=$(echo $9);
abwassertank_groesse=$(echo ${10});
abwassertank_total_liter=$(echo ${11});

echo ";EnergieBox
;Konfigurationsdatei für h2o
;Autogenerated by h2o -setup

[filter]
ventil_pumpe = $ventil_pumpe
hex_generator = $hex_generator
filter_gpd = $filter_gpd
filter_max_menge_filtern = $filter_max_menge_filtern
filter_verhaeltnis = $filter_verhaeltnis
filter_clean_time = $filter_clean_time
filter_zeit_100ml = $filter_zeit_100ml
filter_total_liter = $filter_total_liter

[tank]
abwassertank_vorhanden = $abwassertank_vorhanden
abwassertank_groesse = $abwassertank_groesse
abwassertank_total_liter = $abwassertank_total_liter
" > /Energiebox/h2o/config2.ini
