#!/bin/bash
if [ $metal == "au" ]; then
    printf "\n > 3) Elektroden ~ 1,2 cm tief im Wasser positionieren!\n\n";
    printf "           \          /      \n";
    printf "            \        /       \n";
    printf "   |         \      /        |\n";
    printf "   |~~~~~~~~~~\~~~~/~~~~~~~~~|\n";
    printf "   |           \  /          |\n";
    printf "   |            \/           |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |_________________________|\n\n";
elif [ $metal == "ag" ]; then
    printf "\n > 3) Elektroden maximal ~ 2 mm tief im Wasser positionieren!\n\n";
    printf "              \    /          \n";
    printf "               \  /           \n";
    printf "   |~~~~~~~~~~~~\/~~~~~~~~~~~|\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |_________________________|\n\n";
elif [ $metal == "pt" ]; then
    printf "\n > 3) Elektroden ~ 1,2 cm tief im Wasser positionieren!\n\n";
    printf "           \          /      \n";
    printf "            \        /       \n";
    printf "   |         \      /        |\n";
    printf "   |~~~~~~~~~~\~~~~/~~~~~~~~~|\n";
    printf "   |           \  /          |\n";
    printf "   |            \/           |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |_________________________|\n\n";
elif [ $metal == "cu" ]; then
    printf "\n > 3) Elektroden parallel so tief es geht im Wasser positionieren!\n\n";
    printf "          |           |       \n";
    printf "          |           |       \n";
    printf "   |      |           |      |\n";
    printf "   |~~~~~~|~~~~~~~~~~~|~~~~~~|\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |_________________________|\n\n";
elif [ $metal == "zn" ]; then
    printf "\n > 3) Elektroden parallel so tief es geht im Wasser positionieren!\n\n";
    printf "          |           |       \n";
    printf "          |           |       \n";
    printf "   |      |           |      |\n";
    printf "   |~~~~~~|~~~~~~~~~~~|~~~~~~|\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |_________________________|\n\n";
elif [ $metal == "mg" ]; then
    printf "\n > 3) Elektroden parallel so tief es geht im Wasser positionieren!\n\n";
    printf "          |           |       \n";
    printf "          |           |       \n";
    printf "   |      |           |      |\n";
    printf "   |~~~~~~|~~~~~~~~~~~|~~~~~~|\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |      |           |      |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |                         |\n";
    printf "   |_________________________|\n\n";
fi
